---
title: "WGOA Survey Station-At Sea Day to Day"
author: "Jesse F Lamb"
date: "`r Sys.Date()`"
output: html_document
---
Day to Day: The purpose of this markdown is to determine the next Days sampling. Variables that can be adjusted: Ship Speed (line 72).  Lastly, STATION ORDER MATTERS IN TERMS OF DISTANCE (line 51).  

```{r Setup & Opening Table, message=FALSE, warning=FALSE, include=FALSE}

#Install Packages
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

packages <- c("tidyr",  "dplyr","lubridate","hms", "ggplot2", "ggmap", "lattice", "stringr", "data.table","tibble","readxl", "sf","maps", "mapdata", "mapplots", "mapview", "marmap", "Cairo", "ncdf4","oce", "here","reshape2", "viridis", "export", "rnaturalearth", "kableExtra","rnaturalearthdata", "forcats","sf", "geosphere")
ipak(packages)

# Create Base Layer Maps will all numbered stations labeled, with a more focused region (not whole WGOA)
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

```

## Overview:

Below are a Station Table and Map of future stations

```{r Opening Table, echo=FALSE, warning=FALSE, message=FALSE}
# Load Station Data Table from DY19-05
WGOAdata <- read.csv(here("Data","2025 Station Data","2025-04-01 WGOA DY25-05 GearTime & WPZ.csv"))

### Create Station & Runtime Dataset ############

##All Stations
AllSta<-c(0, 1:9,28:24,38:44,59:53,68:179,180,213:208,216:220,228:225,234:238,271)

###Stations by Day/Interruptions

## Completed Stations
CompleteScenL <- length(c(1,6,5,2:4,7:9,24:28,59:53,84:77,92,91,
                          90:85,100:97,96,95:93,107:105,110,119,117,115)) #Fill in with completed StaTDL stations

## Stations Remaining
StaTDL<-c()
ScenName <- "Day Plan" # Best 
Scenario<-StaTDL # Always Change to Updated Scene
FinalSta<-data.frame("Station"=Scenario,"Stn_Order"= (CompleteScenL+1):(CompleteScenL+length(Scenario))) 
#Stn_Order = cumulative Station order for data entry

# Select Scen Stations (above) from Total Station List
Sta <- WGOAdata %>% left_join(.,FinalSta) %>%
  filter(Station %in% FinalSta$Station) %>%  
  arrange(Stn_Order)

# 2. Choose Departure Date
#DH_SIP <- ymd_hm("2023-05-15 12:00") 
#depart <- DH_SIP + dhours(10) # pre-survey calculations, takes ~8 hours to get to STA 1 from DH
depart <- lubridate::now(tzone = "America/Anchorage") + dhours(1.25)

# 3. Create data.frame that mirrors "Final Station Runtime"
# If using smalled CalVET grid, use "Gear.Sampled2".  Also, change Gear.Sampled on lines 86-89 & 119-120

SRTdata <- Sta %>% 
 mutate(Station_Time = lubridate::dhours(Total_Gear_Time)) %>% 
#<<<<<<< Updated upstream
  mutate(Ship_Speed = 11) %>% # Ship speed is Variable  
  mutate(lat_rad = LAT*pi/180) %>% mutate(long_rad = LON*pi/180) %>% 
  mutate(long_dif = long_rad - shift(long_rad)) %>% 
#>>>>>>> Stashed changes
  mutate(Dist_NM = ifelse(Station == 0,0,0) ) %>% 
  mutate(Dist_NM = distGeo(cbind(LON,LAT),cbind(shift(LON),shift(LAT)))/(1000*1.852)) %>% # distGEO does what code below does in base
#  mutate(Dist_NM = acos((sin(lag(lat_rad))*sin(lat_rad))+(cos(lag(lat_rad))*cos(lat_rad)*cos(long_dif)))/(pi/180)*60) %>%  
  mutate(Steam_T = Dist_NM/Ship_Speed) %>% 
  mutate(Steam_T = lubridate::dhours(Steam_T))

# 4. rearrange data to calculate time to travel to and complete station operations
shipslog <- SRTdata %>% select(Station, Grid.ID, Station_Time, Steam_T, Stn_Order) %>% # SRTdata will be replaced by filtered stations above
  unite("Station",Station:Grid.ID, sep = "_", remove = FALSE) %>% 
  select(Station,Steam_T,Station_Time,Stn_Order) %>% 
  gather(key="Ops", Time_Dur, -Station,-Stn_Order) %>% arrange(Station) %>% 
  separate(Station, c("Station","Grid.ID"), sep = "_") %>% 
  transform(Station = as.numeric(Station)) %>% arrange(Stn_Order) 
shipslog <- na.omit(shipslog)

# 5. Create a table of Station Completion Times 
ShipsLog <- shipslog %>% group_by(Stn_Order, Station, Grid.ID) %>% 
  reframe(Time_Dur = lubridate::dseconds(sum(Time_Dur)))  %>% 
  mutate(Sta_Time =  depart) %>% mutate(cTime_Dur = cumsum(Time_Dur)) %>%
  mutate(Sta_Time = cTime_Dur + Sta_Time) %>% select(Stn_Order, Grid.ID,Sta_Time) %>% 
  rename("Station"="Stn_Order","Grid Station"="Grid.ID","Est.Station Time"="Sta_Time")

#6. Create a table to link Gear.Sampled for daily stations in ShipsLog to know Operations at each station
# Check: Gear.Sampled or Gear.Sampled2???
Sta_GearSamp <- SRTdata %>% select(Station,Grid.ID,LAT,LON,Gear.Sampled) %>% 
filter(Station %in% FinalSta$Station) %>% select(Grid.ID,LAT,LON,Gear.Sampled) %>% 
  rename("Grid Station"="Grid.ID")

ShipsLog <- left_join(ShipsLog,Sta_GearSamp, by = "Grid Station") %>% 
  select(Station,`Grid Station`,LAT,LON,Gear.Sampled,`Est.Station Time`)

# Output Station Table, include: Ships Log
kbl(ShipsLog, caption = "Next Stations", booktabs = T) %>% 
  kableExtra::kable_styling(bootstrap_options = "bordered", latex_options = c("striped", "HOLD_position"))
```

## Ship Track: Station Order


```{r Station Track Map,out.width = "100%", fig.align = "center", echo=FALSE, message=FALSE, warning=FALSE}

# get bathymetry data

b = getNOAA.bathy(lon1 = min(SRTdata$LON)+-1, lon2 = max(SRTdata$LON)+1, 
                  lat1 = min(SRTdata$LAT)+-1, lat2 = max(SRTdata$LAT)+1, 
                 resolution = 15)
# convert bathymetry to data frame
bf = fortify.bathy(b)
# set map limits, whole region
lons = c(min(SRTdata$LON)+-1, max(SRTdata$LON)+1) #-140 = large map
lats = c(min(SRTdata$LAT)+-1,max(SRTdata$LAT)+1) # 52 = large map

# 5. Plot filtered station map with survey track
StaMapF <-ggplot()+geom_contour(data = bf, aes(x=x, y=y, z=z),breaks=c(-50),linewidth=c(0.5),colour="light grey")+ # add 50m contour
  geom_contour(data = bf, aes(x=x, y=y, z=z), breaks=c(-100), linewidth=c(0.5), colour="darkgrey")+ # add 100m contour
  geom_contour(data = bf, aes(x=x, y=y, z=z),breaks=c(-200),linewidth=c(0.3), colour="black")+ # add 200m contour
  geom_sf(data = world)+coord_sf(xlim = lons, ylim = lats, expand = FALSE)+ # add coastline
  #Plot points & station track
  geom_point(data = SRTdata, mapping = aes(LON, LAT, shape = Gear.Sampled), size = 1)+ 
  geom_path(data = SRTdata, mapping = aes(LON, LAT), linewidth = 0.25) +  
  geom_text(data = SRTdata, mapping = aes(LON, LAT, label = Stn_Order ), nudge_y = -0.08, size = 2.5)+ 
  scale_shape_discrete()+ theme_bw()+xlab("Longitude")+ylab("Latitude")+ ggtitle(paste(ScenName,length(Scenario),"Stations")) +
  theme(axis.text.x=element_text(size=8,hjust = 1,vjust = 1, angle = 45, color = "black"), axis.text.y = element_text(size=8, color = "black")) 

StaMapF
```


